[package]
name = "oxid_application"
edition = "2024"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
diesel = { version = "2.3.7", features = ["uuid", "chrono"] }
diesel-async = { version = "0.8.0", features = [
    "postgres",
    "deadpool",
    "migrations",
] }
diesel_migrations = { version = "2.3.1", features = ["postgres"] }
oxid_service_interface.workspace = true
lettre = { version = "0.11" }
pq-sys = { version = "0.7.5", features = ["bundled"] }
openssl-sys = { version = "0.9.112", features = ["vendored"] }
dotenvy = "0.15"
serde = "1.0.228"
uuid = { version = "1.23.0", features = ["serde", "v7"] }
# TODO Update when v0.6.0 of argon2 comes out
argon2 = { version = "0.6.0-rc.8" }
rand_core = { version = "0.10.0" }
password-hash = { version = "0.6.0", features = ["rand_core"] }
thiserror = "2.0.18"
chrono = { version = "0.4.44", features = ["serde"] }
hex = "0.4.3"
getrandom = "0.4.2"
derive-debug = "0.1.2"
actix-web = { version = "4.13.0", features = ["rustls-0_23"] }
tracing = "0.1.44"
rustls = "0.23.37"
serde_json = "1.0.149"

[dev-dependencies]
tokio = { version = "1.50.0", features = ["macros"] }
rstest = "0.26.1"
actix-test = "0.1.5"
