[workspace]
resolver = "3"
members = ["oxid_application", "oxid_service_interface"]

[workspace.dependencies]
oxid_service_interface = { path = "oxid_service_interface" }

[workspace.package]
version = "0.0.1"
authors = ["Richard Paterson"]
description = "A Rust based Authentication Management System"

[profile.dev]
split-debuginfo = "unpacked"
debug = "line-tables-only"

[profile.dev.package."*"]
debug = 0

[profile.debugging]
inherits = "dev"
debug = true
