/*
 * OxID - OpenAPI 3.1
 *
 * OxID is an authentication and identity management service. It provides user registration, login, token refresh, and secured user lookup using JWT-based authentication. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: richy1623@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AuthenticationToken : A token used to prove identity
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticationToken {
    /// Identifier for the token
    #[serde(rename = "tokenId")]
    pub token_id: uuid::Uuid,
    /// The secret key used to validate against (64 Bytes)
    #[serde(rename = "tokenSecret")]
    pub token_secret: String,
    /// The time until which the token is valid
    #[serde(rename = "tokenExpiryTime")]
    pub token_expiry_time: String,
}

impl AuthenticationToken {
    /// A token used to prove identity
    pub fn new(token_id: uuid::Uuid, token_secret: String, token_expiry_time: String) -> AuthenticationToken {
        AuthenticationToken {
            token_id,
            token_secret,
            token_expiry_time,
        }
    }
}

