/*
 * OxID - OpenAPI 3.1
 *
 * OxID is an authentication and identity management service. It provides user registration, login, token refresh, and secured user lookup using JWT-based authentication. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: richy1623@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorDetail : Standard error response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorDetail {
    /// Short error identifier
    #[serde(rename = "error")]
    pub error: String,
    /// Human-readable error explanation
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ErrorDetail {
    /// Standard error response
    pub fn new(error: String) -> ErrorDetail {
        ErrorDetail {
            error,
            message: None,
        }
    }
}

