/*
 * OxID - OpenAPI 3.1
 *
 * OxID is an authentication and identity management service. It provides user registration, login, token refresh, and secured user lookup using JWT-based authentication. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: richy1623@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoginToken : JWT access and refresh token pair
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginToken {
    /// Short-lived JWT used for authenticated requests
    #[serde(rename = "accessToken")]
    pub access_token: String,
    /// Long-lived token used to refresh authentication
    #[serde(rename = "refreshToken")]
    pub refresh_token: String,
}

impl LoginToken {
    /// JWT access and refresh token pair
    pub fn new(access_token: String, refresh_token: String) -> LoginToken {
        LoginToken {
            access_token,
            refresh_token,
        }
    }
}

