/*
 * OxID - OpenAPI 3.1
 *
 * OxID is an authentication and identity management service. It provides user registration, login, token refresh, and secured user lookup using JWT-based authentication. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: richy1623@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// User : Public user profile information
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    /// User's email address
    #[serde(rename = "emailAddress")]
    pub email_address: String,
    /// User's given name
    #[serde(rename = "firstName")]
    pub first_name: String,
    /// User's family name
    #[serde(rename = "surname")]
    pub surname: String,
    /// User's contact phone number
    #[serde(rename = "contactNumber", skip_serializing_if = "Option::is_none")]
    pub contact_number: Option<String>,
    /// User's address
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Optional identification number (e.g. passport number)
    #[serde(rename = "identification", skip_serializing_if = "Option::is_none")]
    pub identification: Option<String>,
}

impl User {
    /// Public user profile information
    pub fn new(email_address: String, first_name: String, surname: String) -> User {
        User {
            email_address,
            first_name,
            surname,
            contact_number: None,
            address: None,
            identification: None,
        }
    }
}

