/*
 * OxID - OpenAPI 3.1
 *
 * OxID is an authentication and identity management service. It provides user registration, login, token refresh, and secured user lookup using JWT-based authentication. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: richy1623@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserRefreshLoginRequest : Payload used to refresh authentication tokens
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserRefreshLoginRequest {
    /// Opaque refresh token issued during login
    #[serde(rename = "refreshToken")]
    pub refresh_token: String,
}

impl UserRefreshLoginRequest {
    /// Payload used to refresh authentication tokens
    pub fn new(refresh_token: String) -> UserRefreshLoginRequest {
        UserRefreshLoginRequest {
            refresh_token,
        }
    }
}

