/*
 * OxID - OpenAPI 3.1
 *
 * OxID is an authentication and identity management service. It provides user registration, login, token refresh, and secured user lookup using JWT-based authentication. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: richy1623@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserLoginRequest : Login credentials for a user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserLoginRequest {
    /// Registered email address
    #[serde(rename = "emailAddress")]
    pub email_address: String,
    /// User password
    #[serde(rename = "password")]
    pub password: String,
}

impl UserLoginRequest {
    /// Login credentials for a user
    pub fn new(email_address: String, password: String) -> UserLoginRequest {
        UserLoginRequest {
            email_address,
            password,
        }
    }
}

