name: Rust

on:
  push:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Standard Tests
    if: ${{ contains(github.event.head_commit.message, '[ci]') }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres:18.1-alpine
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
          POSTGRES_INITDB_ARGS: "-c max_connections=500"
        ports:
          - 5430:5432
        options: >-
          --health-cmd pg_isready --health-interval 1s --health-timeout 1s --health-retries 20

    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache/restore@v4
        id: cache-test-restore
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run tests
        run: cargo test --verbose

      - uses: actions/cache/save@v4
        id: cache-test-save
        if: (success() || failure()) && steps.cache-test-restore.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

  coverage:
    name: Run Coverage Tests
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache/restore@v4
        id: cache-coverage-restore
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-coverage-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-coverage-

      - name: Install Tarpaulin
        run: |
          if ! cargo tarpaulin --version &> /dev/null; then
            echo "Installing cargo-tarpaulin..."
            cargo install cargo-tarpaulin
          else
            echo "cargo-tarpaulin is already installed."
          fi

      - name: Run tests with coverage
        run: cargo tarpaulin

      - uses: actions/cache/save@v4
        id: cache-coverage-save
        if: (success() || failure()) && steps.cache-coverage-restore.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-coverage-${{ hashFiles('**/Cargo.lock') }}

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: cobertura.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cobertura.xml
          fail_ci_if_error: true
